---

# This role provides easyily downloadable firmware files

- name: Firmware dvb-demod-si2168-b40-01.fw for Hauppauge WinTV HD Solo/Duo, PCTV 292e
  get_url:
    url: https://github.com/OpenELEC/dvb-firmware/raw/master/firmware/dvb-demod-si2168-b40-01.fw
    checksum: sha256:8507536630d75a316d0719d6b95c04b90c36baa5b457ad457c9bacadafcef134
    dest: /lib/firmware/dvb-demod-si2168-b40-01.fw
  when: '"2040:0264" in usb or "2013:025f" in usb'

- name: Firmware dvb-demod-si2168-d60-01.fw for Hauppauge WinTV-dualHD
  get_url:
    url: https://github.com/CoreELEC/dvb-firmware/raw/master/firmware/dvb-demod-si2168-d60-01.fw
    checksum: sha256:5E1C860E95A8D92B2716B0075DD00E55F99C2C368E35340F6B527C366FF27EE7
    dest: /lib/firmware/dvb-demod-si2168-d60-01.fw
  when: '"2040:8265" in usb'

- name: Firmware dvb-fe-xc5000-1.6.114.fw for Hauppauge WinTV-HVR-930C
  get_url:
    url: https://github.com/OpenELEC/dvb-firmware/raw/master/firmware/dvb-fe-xc5000-1.6.114.fw
    checksum: sha256:7104bda8df301fe1bd4c09de1708aeb6d0d8e1f9d55505449fecfad82639235f
    dest: /lib/firmware/dvb-fe-xc5000-1.6.114.fw
  when: '"2040:1605" in usb'

- name: Firmware ngenge_18.fw for ngene cards
  get_url:
    url: https://linux4media.de/official_downloads/drivers/ngene_18.fw
    checksum: sha256:213d98ec2cd575eba15d82ee79fed7098e670de43792f8aa773a95cfb7c32060
    dest: /lib/firmware/ngene_18.fw
  when: '"ngene" in modules'
  notify: ['reboot required']

- name: Firmware drxk_a3.mc for drxk
  get_url:
     url: https://github.com/OpenELEC/dvb-firmware/raw/master/firmware/drxk_a3.mc
     checksum: sha256:f8956ad6f92a4ce90a6ab94ed23e2f9a27e9317e936fd3e0119778dd28e7e294
     dest: /lib/firmware/drxk_a3.mc
  when: '"ngene" in modules or "drxk" in modules'
  notify: ['reboot required']

- name: Firmware for Hauppauge Win-TV HVR-4000. NOVA-HD-S2 and Tevii S460
  get_url:
    url: https://github.com/OpenELEC/dvb-firmware/raw/master/firmware/dvb-fe-cx24116.fw
    checksum: sha256:8fa49be12cf332b4c9b0379ef997be9ab6e193ae03aae55b39e033ae31e35da0
    dest: /lib/firmware/dvb-fe-cx24116.fw
  when: '"14f1:8802" in pci or "d460:9022" in pci'
  notify: ['reboot required']

- name: Firmware for Tevii S464/470/471/660
  get_url:
    url: https://github.com/OpenELEC/dvb-firmware/raw/master/firmware/dvb-fe-ds3000.fw
    checksum: sha256:ad8c23bfb51642f48d31fe4f797182352bb13a4d4b7247b25aea18e208e0e882
    dest: /lib/firmware/dvb-fe-ds3000.fw
  when: '"d464:9022" in pci or "14f1:8802" in pci or "d470:9022" in pci or "d471:9022" in pci or "9022:d660" in usb or "0572:6831" in usb'
  notify: ['reboot required']
